
 create TABLE files(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50),
    filePath VARCHAR(150)
       );


create TABLE users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name VARCHAR(50),
    password VARCHAR(255),
    role VARCHAR(100),
    status VARCHAR(50)
    );


create TABLE events(
id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
user_id BIGINT,
file_id BIGINT,
   FOREIGN KEY (user_id)  REFERENCES users (id) ON DELETE CASCADE,
   FOREIGN KEY (file_id)  REFERENCES files (id) ON DELETE CASCADE
   );


